# http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false
#  # http://docs.travis-ci.com/user/customizing-the-build/#Implementing-Complex-Build-Steps
# https://docs.travis-ci.com/user/installing-dependencies/#Installing-Packages-on-Container-Based-Infrastructure
addons:
  apt:
    packages:
    - libxml2-utils
script:
  - sh tools/gpxlint --noout monuments.gpx
