# http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false
#  # http://docs.travis-ci.com/user/customizing-the-build/#Implementing-Complex-Build-Steps
script:
  - sh tools/gpxlint --noout monuments.gpx
