default namespace = "http://www.topografix.com/GPX/1/1"
namespace a = "http://relaxng.org/ns/compatibility/annotations/1.0"


## Stricter subset of http://www.topografix.com/GPX/1/1/gpx.xsd
## 
## Elements MUST appear in order!
##
start =
  element gpx {
    (attribute creator { xsd:anyURI },
     attribute version { xsd:decimal }),
    element metadata {
      name,
      element author { name, link },
      element time { xsd:dateTime },
      element keywords { text }
    },
    element wpt {
      
      ## GPS position, mandatory
      (attribute lat {
         
         ## maybe limit range?
         xsd:decimal
       },
       attribute lon {
         
         ## maybe limit range?
         xsd:decimal
       }),
      
      ## name, mandatory
      name,
      
      ## county list page, mandatory
      element cmt {
        xsd:string {
          
          ## VERY scrupulous.
          pattern =
            "[A-Z][a-z]+(%20)+[Ll]ist\.html?#[a-z'2\-/]+(%20[a-z2-7'\-]+)*"
        }
      },
      
      ## content of map item callout bubble, html snippet, mandatory
      element desc {
        xsd:string {
          
          ## Be VERY scrupulous about the precise content containing a backlink.
          ## This strictness makes <link> obsolete.
          ## 
          ## validate the unescaped form, huh!
          pattern =
            '<a\s+href="http://megalithicireland\.com/[^"]+\?src=gpx">@megalithicireland.com</a>'
        }
      },
      
      ## backlink, optional
      link?,
      element sym {
        
        ## presence is mandatory, but may be empty
        ## 
        ## Could be a very strict enumeration, but currently we go with lowercase words.
        empty
        | xsd:string { pattern = "subject#[a-z]+" }
      }
    }+
  }
name = element name { xsd:anyURI }
link =
  element link {
    attribute href { xsd:anyURI }
  }
